export const SEARCH_BY = 'SEARCH_BY';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SAVE_SEARCH_MOVIES_RESULT = 'SAVE_SEARCH_MOVIES_RESULT';
export const SORT_BY = 'SORT_BY';

export const SAVE_SELECTED_MOVIE = 'SAVE_SELECTED_MOVIE';
export const SAVE_MOVIES_BY_GENRE = 'SAVE_MOVIES_BY_GENRE';
